### ISSUE TITLE
CS231n 1：Python Numpy教程.md

### ISSUE THREAD

**Issue by kosswong** [whyscience/CS231n-Note-Translation_CN#1]
`pivot = arr[len(arr) / 2]` is wrong

Please fix as `pivot = arr[len(arr) // 2]`

**Comment by ghost** [comment]
I dont think it is necessary to do so.
This repo is based on old origin class tutorial which used Python 2. See [here](https://github.com/whyscience/CS231n-Note-Translation_CN/blob/master/CS231n%201%EF%BC%9APython%20Numpy%E6%95%99%E7%A8%8B.md#python%E7%89%88%E6%9C%AC). However, [the up-to-date tutorial](https://cs231n.github.io/python-numpy-tutorial/#python) uses Python 3. [](https://cs231n.github.io/python-numpy-tutorial/#python) The / operator  is different in those 2 versions. Refer to [this](https://wiki.python.org/moin/HowToEditPythonCode#Expressions).

**Comment by kosswong** [comment]
Oic
